const Types = {
  // categories
  FETCH_CATEGORIES: 'FETCH_CATEGORIES',
  FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',

  //Products
  CLEAR_PRODUCTS: 'CLEAR_PRODUCTS',
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  SEARCH_PRODUCTS: 'SEARCH_PRODUCTS',
};

export default Types;
